[package]
name = "rs-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = "0.22.2"
serde_json = "1.0.128"
langchain-rust = { version = "4.4.1", features = ["qdrant", "fastembed"] }
tokio = { version = "1", features = ["full"] }

[lib]
path = "rs_rag/src/lib.rs"